import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import {handleNotes} from '../worker/notes.js';
import {NotesStore} from '../dist/notes.js';
const db=new DatabaseSync(':memory:');
for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const env={DB:{prepare(sql){let v=[];return {bind(...args){v=args;return this;},async first(){return db.prepare(sql).get(...v);},async run(){return {meta:{changes:Number(db.prepare(sql).run(...v).changes)}};}};}}};
const ids=new Set(['bone','muscle']);
const call=(user,id='bone',data,headers={})=>handleNotes(new Request('https://test.local/api/notes?structure='+id,{method:data===undefined?'GET':'PUT',headers:{...(user?{'oai-authenticated-user-id':user}:{}),'Content-Type':'application/json',...headers},...(data===undefined?{}:{body:JSON.stringify(data)})}),env,ids);
assert.equal((await call(null)).status,401);
assert.equal((await call('a','unknown')).status,400);
assert.equal((await call('a','bone',{body:'x',version:0},{Origin:'https://other.test'})).status,403);
assert.equal((await call('a','bone',{body:'x',version:0},{'Content-Type':'text/plain'})).status,415);
for(const data of [null,{body:'x'.repeat(4001),version:0},{body:'x',version:-1},{body:'x',version:Number.MAX_SAFE_INTEGER}])assert.equal((await call('a','bone',data)).status,400);
assert.equal((await call('a','bone',{body:'first',version:0})).status,200);
assert.deepEqual(await (await call('b')).json(),{body:'',version:0});
assert.deepEqual(await (await call('a','muscle')).json(),{body:'',version:0});
assert.equal((await call('a','bone',{body:'stale',version:0})).status,409);
assert.deepEqual(await (await call('a')).json(),{body:'first',version:1});
await call('a','bone',{body:'',version:1});
assert.deepEqual(await (await call('a')).json(),{body:'',version:2});
let fail=false,duringSave=null;
globalThis.fetch=async(url,init={})=>{if(fail)throw new Error('offline');if(init.method&&duringSave){const fn=duringSave;duringSave=null;fn();}return call('client',new URL(url,'https://test.local').searchParams.get('structure'),init.body?JSON.parse(init.body):undefined);};
const a=new NotesStore(),b=new NotesStore();await a.load('bone');await b.load('bone');
a.edit('bone','draft');await a.load('muscle');a.edit('muscle','other');assert.equal(a.entry('bone').text,'draft');
fail=true;assert.equal(await a.save('bone'),false);assert.equal(a.entry('bone').text,'draft');assert.ok(a.hasUnsaved);
fail=false;assert.equal(await a.save('bone'),true);
b.edit('bone','second tab');assert.equal(await b.save('bone'),false);assert.equal(b.entry('bone').conflict.body,'draft');
assert.equal(await b.keepDraft('bone'),true);assert.equal(b.entry('bone').text,'second tab');
a.edit('bone','local');assert.equal(await a.save('bone'),false);a.useServer('bone');assert.equal(a.entry('bone').text,'second tab');
a.edit('bone','sent');duringSave=()=>a.edit('bone','typed while saving');assert.equal(await a.save('bone'),true);assert.equal(a.entry('bone').saved,'sent');assert.equal(a.entry('bone').text,'typed while saving');
await a.save('bone');await a.save('muscle');assert.equal(a.hasUnsaved,false);
const c=new NotesStore();fail=true;await c.load('bone');assert.equal(c.entry('bone').loaded,false);fail=false;await c.load('bone');assert.equal(c.entry('bone').text,'typed while saving');
console.log('PASS: notes migrations, account isolation, validation, version conflicts, clearing, draft retention, offline retry and edits during save');
