import assert from 'node:assert/strict';
import {readPractice,practiceStatus,practiceCounts,pickPracticePoint,markPractice} from '../dist/piece-practice.js';
const points=[{id:'a'},{id:'b'},{id:'c'}];let stored=null;const storage={getItem:()=>stored,setItem:(key,value)=>stored=value};const records=readPractice(storage);
assert.deepEqual(practiceCounts(records,'pe',points),{known:0,review:0,unseen:3});
assert.equal(markPractice(records,storage,'pe','a','known'),true);
markPractice(records,storage,'pe','b','review');
assert.equal(pickPracticePoint(records,'pe',points,null,()=>0).id,'b');
assert.equal(pickPracticePoint(records,'pe',points,'b',()=>0).id,'c');
assert.equal(practiceStatus(readPractice(storage),'pe','a'),'known');
assert.equal(practiceStatus(readPractice(storage),'mao','a'),null);
assert.deepEqual(practiceCounts(records,'pe',points),{known:1,review:1,unseen:1});
markPractice(records,storage,'pe','b','known');markPractice(records,storage,'pe','c','known');
assert.notEqual(pickPracticePoint(records,'pe',points,'a',()=>0).id,'a');
assert.equal(pickPracticePoint(records,'pe',[],null),null);
assert.deepEqual(readPractice({getItem:()=>'{bad json'}),{});
assert.deepEqual(readPractice(undefined),{});
assert.equal(markPractice(records,undefined,'pe','a','review'),false);
assert.equal(practiceStatus(records,'pe','a'),'review');
console.log('PASS: saved per-piece progress, review priority, no immediate repeat with alternatives, completed set restart and unavailable storage');
