import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import {handleProgress} from '../worker/progress.js';
import {topics} from '../dist/content.js';
import {boneRecord} from '../dist/catalog.js';
import {ProgressStore} from '../dist/progress.js';
import {lessons,lessonOrder,lessonSources} from '../dist/lesson-data.js';
const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync('drizzle/0000_mighty_marrow.sql','utf8'));
const env={DB:{prepare(sql){let values=[];return {bind(...v){values=v;return this;},async first(){return sqlite.prepare(sql).get(...values);},async all(){return {results:sqlite.prepare(sql).all(...values)};},async run(){return sqlite.prepare(sql).run(...values);}};}}};
const bones=JSON.parse(fs.readFileSync('dist/skeleton.json')).meshes.map(m=>m.name),muscles=JSON.parse(fs.readFileSync('dist/shoulder.json')).meshes.map(m=>m.id),ids=new Set([...bones,...muscles]);
for(const step of Object.values(lessons).flatMap(lesson=>lesson.steps)){for(const id of [step.target,step.focus,...step.region||[]].filter(Boolean))assert.ok(ids.has(id)||(id.startsWith('group:')&&Object.hasOwn(topics,id.slice(6))),id);}
const call=(user,data,extra={})=>handleProgress(new Request('https://anatomia.test/api/progress',{method:data===undefined?'GET':'POST',headers:{...(user?{'oai-authenticated-user-id':user}:{}),'Content-Type':'application/json',...extra},...(data===undefined?{}:{body:JSON.stringify(data)})}),env,ids);
assert.equal((await call(null)).status,401);
assert.equal((await call('a',null)).status,400);
assert.equal((await call('a',{type:'lesson',currentStep:99,completedSteps:[]})).status,400);
assert.equal((await call('a',{}, {Origin:'https://other.test'})).status,403);
await call('a',{type:'lesson',currentStep:1,completedSteps:[0]});await call('a',{type:'lesson',currentStep:3,completedSteps:[2]});
assert.deepEqual((await (await call('a')).json()).lesson,{currentStep:3,completedSteps:[0,2]});
assert.deepEqual((await (await call('b')).json()).lesson.completedSteps,[]);
const event={type:'review',eventId:crypto.randomUUID(),structureId:'Scapula.r',correct:false};
await call('a',event);await call('a',event);
let state=await (await call('a')).json();assert.equal(state.reviews[0].attempts,1);assert.equal(state.reviews[0].last_correct,0);
await call('a',{...event,eventId:crypto.randomUUID(),correct:true});
state=await (await call('a')).json();assert.equal(state.reviews[0].last_correct,1);assert.equal(state.reviews[0].first_try,1);assert.equal((await (await call('b')).json()).reviews.length,0);
// Exercise the client against real SQL, including failed writes and safe retry.
let fail=false,enqueueDuringLoad=null;
globalThis.fetch=async(url,init={})=>{if(fail&&init.method==='POST')return new Response('',{status:503});if(!init.method&&enqueueDuringLoad){const f=enqueueDuringLoad;enqueueDuringLoad=null;f();}return call('client',init.body?JSON.parse(init.body):undefined);};
const store=new ProgressStore();assert.ok(await store.load());
fail=true;assert.equal(await store.saveLesson(1,[0]),false);assert.equal(store.pending.length,1);assert.equal(store.status,'error');
fail=false;assert.ok(await store.retry());assert.equal(store.pending.length,0);assert.equal(store.data.lesson.currentStep,1);
const q={id:'Scapula.r',hadError:true};await store.recordReview(q);q.hadError=false;await store.recordReview(q);assert.deepEqual(store.mistakes,['Scapula.r']);
await store.recordReview({id:'Scapula.r',hadError:false});assert.deepEqual(store.mistakes,[]);
enqueueDuringLoad=()=>store.saveLesson(3,[2]);await store.saveLesson(2,[1]);assert.equal(store.pending.length,0);assert.equal(store.data.lesson.currentStep,3);assert.deepEqual(store.data.lesson.completedSteps,[0,1,2]);
await store.saveLesson(4,[0,1,2,3],'joelho-inicial');
assert.equal(store.lesson('joelho-inicial').currentStep,4);assert.deepEqual(store.lesson('ombro-inicial').completedSteps,[0,1,2]);
assert.equal((await call('client',{type:'lesson',lessonId:'joelho-inicial',currentStep:10,completedSteps:[]})).status,400);
assert.equal((await call('client',{type:'lesson',lessonId:'unknown',currentStep:0,completedSteps:[]})).status,400);
assert.equal((await call('client',{type:'lesson',lessonId:'__proto__',currentStep:0,completedSteps:[]})).status,400);
await store.saveLesson(5,[0,1,2,3,4],'tornozelo-inicial');
assert.equal(store.lesson('tornozelo-inicial').currentStep,5);assert.equal(store.lesson('joelho-inicial').currentStep,4);assert.deepEqual(store.lesson('ombro-inicial').completedSteps,[0,1,2]);
for(const id of lessonOrder){const l=lessons[id];assert.ok(lessonSources[id]);assert.equal(l.id,id);assert.equal((await call('curriculum',{type:'lesson',lessonId:id,currentStep:l.steps.length-1,completedSteps:l.steps.map((_,i)=>i)})).status,200);assert.equal((await call('curriculum',{type:'lesson',lessonId:id,currentStep:l.steps.length,completedSteps:[]})).status,400);}
await call('navigation',{type:'lesson',lessonId:'joelho-inicial',currentStep:5,completedSteps:[0,1,2,3,4]});
await call('navigation',{type:'lesson',lessonId:'joelho-inicial',currentStep:1,completedSteps:[]});
const navigated=await (await call('navigation')).json();assert.equal(navigated.lessons['joelho-inicial'].currentStep,1);assert.deepEqual(navigated.lessons['joelho-inicial'].completedSteps,[0,1,2,3,4]);
const curriculum=await (await call('curriculum')).json();for(const id of lessonOrder)assert.equal(curriculum.lessons[id].completedSteps.length,lessons[id].steps.length);
const eligible=new Map(JSON.parse(fs.readFileSync('dist/skeleton.json')).meshes.map(m=>[m.name,boneRecord(m).quizEligible]));for(const l of Object.values(lessons))for(const step of l.steps)if(step.target&&!step.target.startsWith('muscle:'))assert.ok(eligible.get(step.target),step.target);
assert.equal(new Set(lessonOrder).size,Object.keys(lessons).length);
await call('resume',{type:'lesson',lessonId:'ombro-inicial',currentStep:4,completedSteps:[0,1,2,3]});
await call('resume',{type:'lesson',lessonId:'joelho-inicial',currentStep:2,completedSteps:[0,1]});
sqlite.prepare('UPDATE lesson_progress SET updated_at=? WHERE user_id=? AND lesson_id=?').run(100,'resume','ombro-inicial');
sqlite.prepare('UPDATE lesson_progress SET updated_at=? WHERE user_id=? AND lesson_id=?').run(200,'resume','joelho-inicial');
let resume=await (await call('resume')).json();assert.equal(resume.lastLessonId,'joelho-inicial');assert.equal(resume.lessons[resume.lastLessonId].currentStep,2);
await call('resume',{type:'lesson',lessonId:'ombro-inicial',currentStep:4,completedSteps:[]});
resume=await (await call('resume')).json();assert.equal(resume.lastLessonId,'ombro-inicial');assert.deepEqual(resume.lessons['ombro-inicial'].completedSteps,[0,1,2,3]);
assert.equal((await (await call('new-user')).json()).lastLessonId,'ombro-inicial');
console.log('PASS: last lesson, migration, user isolation, validation, idempotency, mistake resolution, retry, concurrent queue independent lessons, compatibility with existing shoulder progress all lessons and accessible activity targets');
